"""Proves the Day 6 guarantees against the real Postgres container:
- cancel_order is one atomic conditional UPDATE (pending->cancelled works,
  already-cancelled/already-shipped is a clean "not eligible", never a crash)
- issue_refund is idempotent on idempotency_key, including under real
  concurrent execution (not just sequential retries) -- both when called
  directly with an explicit key, AND when the key is generated by the
  orchestrator itself and reused across a simulated transient-failure retry
- the refund velocity check (dollar cap OR count cap) runs inside the same
  transaction as the insert

Seeds fresh customers/orders per scenario (the $100 / 2-refund caps are tight
enough that scenarios would interfere if they shared a customer), asserts
every guarantee, then tears everything down. Run with:
uv run python scripts/test_day6_tools.py
"""

import asyncio
import itertools
import json
import sys
from decimal import Decimal
from pathlib import Path
from types import SimpleNamespace

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import delete, func, select

from app.db.models import Customer, Order, Refund
from app.db.session import async_session_maker
from app.orchestrator import loop
from app.orchestrator.tools import (
    REFUND_VELOCITY_LIMIT_30D,
    REFUND_VELOCITY_MAX_COUNT_30D,
    cancel_order,
    get_order_status,
    issue_refund,
)

created_customer_ids: list[int] = []
_email_counter = itertools.count()


async def seed_customer(order_specs: list[tuple[str, str]]) -> tuple[int, list[int]]:
    """order_specs: list of (status, total_amount) pairs."""
    async with async_session_maker() as session:
        customer = Customer(
            name="Day6 Test Customer", email=f"day6-test-{next(_email_counter)}@example.com"
        )
        session.add(customer)
        await session.flush()

        orders = [
            Order(customer_id=customer.id, status=status, total_amount=Decimal(amount))
            for status, amount in order_specs
        ]
        session.add_all(orders)
        await session.flush()

        order_ids = [o.id for o in orders]
        customer_id = customer.id
        await session.commit()

    created_customer_ids.append(customer_id)
    return customer_id, order_ids


async def teardown_all() -> None:
    async with async_session_maker() as session:
        for customer_id in created_customer_ids:
            order_ids_subq = select(Order.id).where(Order.customer_id == customer_id)
            await session.execute(delete(Refund).where(Refund.order_id.in_(order_ids_subq)))
            await session.execute(delete(Order).where(Order.customer_id == customer_id))
            await session.execute(delete(Customer).where(Customer.id == customer_id))
        await session.commit()
    print(f"teardown complete for customer_ids={created_customer_ids}")


async def count_refunds_with_key(idempotency_key: str) -> int:
    async with async_session_maker() as session:
        return await session.scalar(
            select(func.count()).select_from(Refund).where(Refund.idempotency_key == idempotency_key)
        )


async def test_order_status_and_cancel() -> None:
    customer_id, (pending_id, shipped_id) = await seed_customer(
        [("pending", "100.00"), ("shipped", "50.00")]
    )

    result = await get_order_status(pending_id)
    print("get_order_status(pending order) ->", result)
    assert result["status"] == "pending"
    assert result["shipment"] is None

    result = await get_order_status(999_999_999)
    print("get_order_status(nonexistent) ->", result)
    assert result == {"error": "order not found"}

    result = await cancel_order(pending_id)
    print("cancel_order(pending order) ->", result)
    assert result == {"order_id": pending_id, "status": "cancelled"}

    result = await cancel_order(pending_id)
    print("cancel_order(already-cancelled order) ->", result)
    assert result == {"error": "order not eligible for cancellation"}, "double-cancel must not succeed"

    result = await cancel_order(shipped_id)
    print("cancel_order(already-shipped order) ->", result)
    assert result == {"error": "order not eligible for cancellation"}


async def test_idempotency_direct_sequential_and_concurrent() -> None:
    """Direct calls with an explicit key -- proves the DB-layer mechanism
    (unique constraint + insert/catch/lookup) works at all."""
    customer_id, (order_id,) = await seed_customer([("delivered", "1000.00")])

    key_sequential = "day6-test-sequential-key"
    first = await issue_refund(order_id, "10.00", key_sequential)
    print("issue_refund (1st call) ->", first)
    assert first["replayed"] is False

    second = await issue_refund(order_id, "10.00", key_sequential)
    print("issue_refund (2nd call, same key) ->", second)
    assert second["replayed"] is True
    assert second["refund_id"] == first["refund_id"]

    row_count = await count_refunds_with_key(key_sequential)
    assert row_count == 1, "exactly one refund row must exist for this key"

    key_concurrent = "day6-test-concurrent-key"
    results = await asyncio.gather(
        issue_refund(order_id, "10.00", key_concurrent),
        issue_refund(order_id, "10.00", key_concurrent),
    )
    print("issue_refund (concurrent, same key) ->", results)
    assert len({r["refund_id"] for r in results}) == 1, "both must resolve to the same row"
    assert sum(1 for r in results if r["replayed"]) == 1

    row_count = await count_refunds_with_key(key_concurrent)
    assert row_count == 1, "concurrent duplicate submissions must not create two rows"


async def test_orchestrator_generates_and_reuses_key_on_retry() -> None:
    """The actual fix under review: the ORCHESTRATOR generates the
    idempotency key (from tool_call.id), not the model, and reuses that same
    orchestrator-generated key when it retries a transiently-failed attempt
    at executing the same tool call. Goes through loop._run_tool_call, not a
    hardcoded key string."""
    customer_id, (order_id,) = await seed_customer([("delivered", "1000.00")])

    fake_tool_call = SimpleNamespace(
        id="call_test_retry_001",
        function=SimpleNamespace(
            name="issue_refund",
            arguments=json.dumps({"order_id": order_id, "amount": "30.00"}),
        ),
    )

    real_issue_refund = loop.TOOL_DISPATCH["issue_refund"]
    keys_seen: list[str] = []
    attempt_count = 0

    async def flaky_issue_refund(**kwargs):
        nonlocal attempt_count
        attempt_count += 1
        keys_seen.append(kwargs["idempotency_key"])
        if attempt_count == 1:
            raise ConnectionError("simulated transient DB connection drop")
        return await real_issue_refund(**kwargs)

    loop.TOOL_DISPATCH["issue_refund"] = flaky_issue_refund
    try:
        result = await loop._run_tool_call(fake_tool_call)
    finally:
        loop.TOOL_DISPATCH["issue_refund"] = real_issue_refund

    print("orchestrator retry result ->", result)
    print("idempotency keys used across attempts ->", keys_seen)

    assert attempt_count == 2, "expected exactly one retry after the simulated transient failure"
    assert keys_seen[0] == keys_seen[1], "the retry must reuse the same orchestrator-generated key"
    assert keys_seen[0] == f"toolcall-{fake_tool_call.id}", "key must derive from tool_call.id, not the model"
    assert result["replayed"] is False, "the retry is the attempt that actually lands"

    row_count = await count_refunds_with_key(keys_seen[0])
    assert row_count == 1, "the failed first attempt must not have left a partial row"


async def test_velocity_dollar_cap() -> None:
    customer_id, (order_id,) = await seed_customer([("delivered", "1000.00")])

    print(f"REFUND_VELOCITY_LIMIT_30D = {REFUND_VELOCITY_LIMIT_30D}")
    first = await issue_refund(order_id, "80.00", "day6-test-dollar-cap-1")
    print("issue_refund (80.00, under $100 cap) ->", first)
    assert first["replayed"] is False

    second = await issue_refund(order_id, "80.00", "day6-test-dollar-cap-2")
    print("issue_refund (would total 160.00, over $100 cap) ->", second)
    assert second == {"error": "refund velocity limit exceeded", "requires_escalation": True}
    assert await count_refunds_with_key("day6-test-dollar-cap-2") == 0


async def test_velocity_count_cap() -> None:
    """Proves the count-based OR condition is real and independent of dollar
    amount -- small refunds well under the $100 cap must still get blocked
    once REFUND_VELOCITY_MAX_COUNT_30D is reached."""
    customer_id, (order_id,) = await seed_customer([("delivered", "1000.00")])

    print(f"REFUND_VELOCITY_MAX_COUNT_30D = {REFUND_VELOCITY_MAX_COUNT_30D}")
    for i in range(REFUND_VELOCITY_MAX_COUNT_30D):
        result = await issue_refund(order_id, "10.00", f"day6-test-count-cap-{i}")
        print(f"issue_refund (10.00, attempt {i + 1}) ->", result)
        assert result["replayed"] is False

    blocked = await issue_refund(order_id, "10.00", "day6-test-count-cap-final")
    print(f"issue_refund (10.00, attempt {REFUND_VELOCITY_MAX_COUNT_30D + 1}, well under $100 total) ->", blocked)
    assert blocked == {"error": "refund velocity limit exceeded", "requires_escalation": True}, (
        "must be blocked by the count cap even though the dollar total is nowhere near the limit"
    )
    assert await count_refunds_with_key("day6-test-count-cap-final") == 0


async def main() -> None:
    try:
        await test_order_status_and_cancel()
        await test_idempotency_direct_sequential_and_concurrent()
        await test_orchestrator_generates_and_reuses_key_on_retry()
        await test_velocity_dollar_cap()
        await test_velocity_count_cap()
        print("\nOK: all Day 6 guarantees verified against the real database")
    finally:
        await teardown_all()


if __name__ == "__main__":
    asyncio.run(main())
